version: '3'
services:
  shadowsocks:
    image: agate/shadowsocks:201709
    build: .
  shadowsocks-server:
    image: agate/shadowsocks:201709
    network_mode: host
    command: server
    environment:
      - SS_PORT=30001
      - SS_PASSWORD=abcd
  shadowsocks-local:
    image: agate/shadowsocks:201709
    network_mode: host
    command: local
    environment:
      - SS_SERVER_ADDR=localhost
      - SS_SERVER_PORT=30001
      - SS_PASSWORD=abcd
