#!/usr/bin/env bash

TYPE=$1
ARGS=${@:2}

if [ "$TYPE" != 'server' ] && [ "$TYPE" != 'local' ]; then
  echo "usage: server | local"
  exit 1
fi

SS_CMD=ss${TYPE}

[ "${SS_SERVER_ADDR}" ] && SS_CMD="${SS_CMD} -s ${SS_SERVER_ADDR}"
[ "${SS_SERVER_PORT}" ] && SS_CMD="${SS_CMD} -p ${SS_SERVER_PORT}"
[ "${SS_LOCAL_ADDR}" ] && SS_CMD="${SS_CMD} -b ${SS_LOCAL_ADDR}"
[ "${SS_LOCAL_PORT}" ] && SS_CMD="${SS_CMD} -l ${SS_LOCAL_PORT}"
[ "${SS_PORT}" ] && SS_CMD="${SS_CMD} -p ${SS_PORT}"
[ "${SS_PASSWORD}" ] && SS_CMD="${SS_CMD} -k ${SS_PASSWORD}"
[ "${SS_METHOD}" ] && SS_CMD="${SS_CMD} -m ${SS_METHOD}"
[ "${SS_TIMEOUT}" ] && SS_CMD="${SS_CMD} -t ${SS_TIMEOUT}"
[ "${SS_FAST_OPEN}" ] && SS_CMD="${SS_CMD} --fast-open"
[ "${SS_WORKERS}" ] && SS_CMD="${SS_CMD} --workers=${SS_WORKERS}"
[ "${SS_FORBIDDEN_IP}" ] && SS_CMD="${SS_CMD} --forbidden-ip=${SS_FORBIDDEN_IP}"
[ "${SS_MANAGER_ADDRESS}" ] && SS_CMD="${SS_CMD} --manager-address=${SS_MANAGER_ADDRESS}"
[ "${SS_PREFER_IPV6}" ] && SS_CMD="${SS_CMD} --prefer-ipv6"
[ "${SS_VERBOSE}" ] && SS_CMD="${SS_CMD} -v"

echo RUNNING: "$SS_CMD" $ARGS
$SS_CMD $ARGS
